batch_size_train: 16
batch_size_val: 12
data: /kaggle/working/CameraTraps/PW_FT_detection/data/COD10K.yaml
device_train: 0
device_val: 0
epochs: 20
exp_name: COD10K_finetune
imgsz: 640
lr0: 0.01
model: YOLO
model_name: MDV6-yolov9-c
optimizer: auto
patience: 5
plot: true
resume: false
save_json: true
save_period: 1
task: train
val: true
weights: /root/.cache/torch/hub/checkpoints/MDV6-yolov9e.pt
workers: 8
test_data: /kaggle/working/CameraTraps/PW_FT_detection/data/COD10K/images/test 
